id: PA98FCA1A
initial_creation_type: input
source_metadata:
  title: 'MSV 5,00: Uttaragrantha 1'
  language: bo
  volumes:
    e46ad3b4d1ad4e7a9162e0b52bf45600:
      title: CI_Kaśmīr Upāliparipṛcchā
      base_file: CI_Kaśmīr Upāliparipṛcchā.txt
      work_id: W066659B7
  chapter_to_tile:
    CI: Uttaragrantha 1
created_at: '2022-03-01T22:52:13.410758'
last_modified_at: '2022-03-01T22:52:13.410765'
